
[origins]

	[origins."origins:shulk"]
		"origins:strong_arms" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true
		"origins:strong_arms_break_speed" = true
		"origins:natural_armor" = true
		enabled = true
		"origins:shulker_inventory" = true

	[origins."origins:merling"]
		"origins:air_from_potions" = true
		"origins:swim_speed" = true
		"origins:water_vision" = true
		"origins:like_water" = true
		"origins:aqua_affinity" = true
		"origins:water_breathing" = true
		"origins:conduit_power_on_land" = true
		enabled = true
		"origins:aquatic" = true

	[origins."origins:arachnid"]
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true
		"origins:master_of_webs" = true
		enabled = true
		"origins:climbing" = true

	[origins."origins:phantom"]
		"origins:phasing" = true
		"origins:fragile" = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:invisibility" = true
		"origins:hunger_over_time" = true
		enabled = true
		"origins:burn_in_daylight" = true
		"origins:phantomize_overlay" = true

	[origins."origins:enderian"]
		"origins:water_vulnerability" = true
		"origins:throw_ender_pearl" = true
		"origins:pumpkin_hate" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true
		enabled = true
		"origins:extra_reach" = true

	[origins."origins:blazeborn"]
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:fire_immunity" = true
		"origins:damage_from_snowballs" = true
		"origins:nether_spawn" = true
		"origins:damage_from_potions" = true
		enabled = true

	[origins."origins:feline"]
		"origins:cat_vision" = true
		"origins:velvet_paws" = true
		"origins:fall_immunity" = true
		"origins:weak_arms" = true
		"origins:nine_lives" = true
		enabled = true
		"origins:sprint_jump" = true
		"origins:scare_creepers" = true

	[origins."origins:elytrian"]
		"origins:more_kinetic_damage" = true
		"origins:elytra" = true
		"origins:claustrophobia" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:launch_into_air" = true
		enabled = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:avian"]
		"origins:fresh_air" = true
		"origins:vegetarian" = true
		"origins:lay_eggs" = true
		"origins:slow_falling" = true
		"origins:tailwind" = true
		"origins:like_air" = true
		enabled = true

	[origins."toomanyorigins:hare"]
		enabled = true
		"toomanyorigins:hot_hops" = true
		"toomanyorigins:superfall" = true
		"toomanyorigins:frail" = true
		"origins:vegetarian" = true
		"toomanyorigins:drenchable_fur" = true
		"toomanyorigins:waterskipper" = true
		"toomanyorigins:small_appetite" = true
		"toomanyorigins:extra_step_height" = true
		"toomanyorigins:prevent_movement_checks" = true
		"toomanyorigins:cancel_out_sprint_disable_on_hit" = true

	[origins."toomanyorigins:swarm"]
		enabled = true
		"toomanyorigins:hover" = true
		"toomanyorigins:pollination" = true
		"toomanyorigins:calming_aura" = true
		"toomanyorigins:stinging_pains" = true
		"toomanyorigins:unity" = true
		"toomanyorigins:beekeeper" = true
		"origins:arthropod" = true

	[origins."toomanyorigins:dragonborn"]
		enabled = true
		"toomanyorigins:draconic_breath" = true
		"toomanyorigins:block_synergistics" = true
		"toomanyorigins:weaponry_pride" = true
		"toomanyorigins:zenith_scales" = true
		"toomanyorigins:rough_claws" = true

	[origins."toomanyorigins:withered"]
		enabled = true
		"toomanyorigins:affliction" = true
		"toomanyorigins:soul_siphon" = true
		"origins:nether_spawn" = true
		"toomanyorigins:hell_raised" = true
		"toomanyorigins:spirit_strider" = true
		"toomanyorigins:deathly_digestion" = true
		"toomanyorigins:unholy" = true

	[origins."toomanyorigins:hisskin"]
		enabled = true
		"toomanyorigins:buildup" = true
		"toomanyorigins:aerial_stability" = true
		"toomanyorigins:stubby_legs" = true
		"toomanyorigins:conductive" = true
		"toomanyorigins:ailurophobia" = true
		"toomanyorigins:redirect_lightning_chance" = true

